# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle
name: Java CI with Gradle
on:
  push:
    branches: [ photos-with-users ]
  pull_request:
    branches: [ photos-with-users ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
    - name: Create wrapper for gradle
      run: gradle wrapper --gradle-version 6.5.1 --distribution-type all
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build 
    - name: Show file content
      run: cat result.json
      if: always()
    - name: Create environment variable
      run: |
        echo "::set-env name=TIMESTAMP::$(date +%s)"
        echo "::set-env name=REPONAME::$(basename `git rev-parse --show-toplevel`)"
      if: always()
    - name: Copy file to  s3
      shell: bash
      env:
        log_file_name: ${{env.REPONAME}}-${{env.TIMESTAMP}}.json  
        aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_s3_bucket: ${{ secrets.AWS_S3_BUCKET }}
      run: |
        sudo apt-get update && sudo apt-get -y install awscli
        aws configure set aws_access_key_id $aws_key_id
        aws configure set aws_secret_access_key $aws_secret_access_key 
        aws configure set default.region us-east-1
        aws s3 cp result.json s3://$aws_s3_bucket/$REPONAME/$log_file_name
      if: always()
